server:
  port: 8002
  
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/zuuldb
    username: postgres
    password: danielfd24
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none 
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost