server:
  port: 8003
  
  
spring:
  application:
    name: resource-service
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost
